In [47]:
import pandas as pd
import numpy as np

In [32]:
df=pd.read_csv("/content/osteoporosis.csv")

In [33]:
df.head()

Id  Age  Gender Hormonal Changes Family History    Race/Ethnicity  \
0  1734616   69  Female           Normal            Yes             Asian   
1  1419098   32  Female           Normal            Yes             Asian   
2  1797916   89  Female   Postmenopausal             No         Caucasian   
3  1805337   78  Female           Normal             No         Caucasian   
4  1351334   38    Male   Postmenopausal            Yes  African American   

   Body Weight Calcium Intake Vitamin D Intake Physical Activity Smoking  \
0  Underweight            Low       Sufficient         Sedentary     Yes   
1  Underweight            Low       Sufficient         Sedentary      No   
2       Normal       Adequate       Sufficient            Active      No   
3  Underweight       Adequate     Insufficient         Sedentary     Yes   
4       Normal            Low       Sufficient            Active     Yes   

  Alcohol Consumption    Medical Conditions      Medications Prior Fractures  \
0            Moderate  Rheumatoid Arthritis  Corticosteroids             Yes   
1                 NaN                   NaN              NaN             Yes   
2            Moderate       Hyperthyroidism  Corticosteroids              No   
3                 NaN  Rheumatoid Arthritis  Corticosteroids              No   
4                 NaN  Rheumatoid Arthritis              NaN             Yes   

   Osteoporosis  
0             1  
1             1  
2             1  
3             1  
4             1

In [34]:
df.isna().sum()

Id                       0
Age                      0
Gender                   0
Hormonal Changes         0
Family History           0
Race/Ethnicity           0
Body Weight              0
Calcium Intake           0
Vitamin D Intake         0
Physical Activity        0
Smoking                  0
Alcohol Consumption    988
Medical Conditions     647
Medications            985
Prior Fractures          0
Osteoporosis             0
dtype: int64

In [35]:
df.columns

Index(['Id', 'Age', 'Gender', 'Hormonal Changes', 'Family History',
       'Race/Ethnicity', 'Body Weight', 'Calcium Intake', 'Vitamin D Intake',
       'Physical Activity', 'Smoking', 'Alcohol Consumption',
       'Medical Conditions', 'Medications', 'Prior Fractures', 'Osteoporosis'],
      dtype='object')

In [36]:
df=df.drop(columns={'Id'},axis=1)

In [37]:
df.head()

Age  Gender Hormonal Changes Family History    Race/Ethnicity  Body Weight  \
0   69  Female           Normal            Yes             Asian  Underweight   
1   32  Female           Normal            Yes             Asian  Underweight   
2   89  Female   Postmenopausal             No         Caucasian       Normal   
3   78  Female           Normal             No         Caucasian  Underweight   
4   38    Male   Postmenopausal            Yes  African American       Normal   

  Calcium Intake Vitamin D Intake Physical Activity Smoking  \
0            Low       Sufficient         Sedentary     Yes   
1            Low       Sufficient         Sedentary      No   
2       Adequate       Sufficient            Active      No   
3       Adequate     Insufficient         Sedentary     Yes   
4            Low       Sufficient            Active     Yes   

  Alcohol Consumption    Medical Conditions      Medications Prior Fractures  \
0            Moderate  Rheumatoid Arthritis  Corticosteroids             Yes   
1                 NaN                   NaN              NaN             Yes   
2            Moderate       Hyperthyroidism  Corticosteroids              No   
3                 NaN  Rheumatoid Arthritis  Corticosteroids              No   
4                 NaN  Rheumatoid Arthritis              NaN             Yes   

   Osteoporosis  
0             1  
1             1  
2             1  
3             1  
4             1

# printing the unique values of each column

In [38]:
for i in df.columns:
  print(i,'values: ',df[i].unique())

Age values:  [69 32 89 78 38 41 20 39 70 19 47 55 81 77 50 75 66 76 59 79 64 68 72 24
 90 56 35 21 31 26 88 61 25 52 53 67 23 71 80 51 65 57 43 58 46 62 82 18
 28 22 45 29 40 54 44 60 30 49 83 74 87 73 36 85 34 86 33 37 84 48 42 63
 27]
Gender values:  ['Female' 'Male']
Hormonal Changes values:  ['Normal' 'Postmenopausal']
Family History values:  ['Yes' 'No']
Race/Ethnicity values:  ['Asian' 'Caucasian' 'African American']
Body Weight values:  ['Underweight' 'Normal']
Calcium Intake values:  ['Low' 'Adequate']
Vitamin D Intake values:  ['Sufficient' 'Insufficient']
Physical Activity values:  ['Sedentary' 'Active']
Smoking values:  ['Yes' 'No']
Alcohol Consumption values:  ['Moderate' nan]
Medical Conditions values:  ['Rheumatoid Arthritis' nan 'Hyperthyroidism']
Medications values:  ['Corticosteroids' nan]
Prior Fractures values:  ['Yes' 'No']
Osteoporosis values:  [1 0]


# Checking %of null rows

In [46]:
for i in ['Alcohol Consumption','Medical Conditions','Medications']:
  print((df[i].isna().sum()/df[i].shape)*100)

[50.45965271]
[33.04392237]
[50.30643514]


In [53]:
df[['Alcohol Consumption','Medical Conditions','Medications']]

Alcohol Consumption    Medical Conditions      Medications
0               Moderate  Rheumatoid Arthritis  Corticosteroids
1                    NaN                   NaN              NaN
2               Moderate       Hyperthyroidism  Corticosteroids
3                    NaN  Rheumatoid Arthritis  Corticosteroids
4                    NaN  Rheumatoid Arthritis              NaN
...                  ...                   ...              ...
1953            Moderate  Rheumatoid Arthritis              NaN
1954                 NaN                   NaN  Corticosteroids
1955                 NaN       Hyperthyroidism              NaN
1956                 NaN  Rheumatoid Arthritis  Corticosteroids
1957                 NaN  Rheumatoid Arthritis  Corticosteroids

[1958 rows x 3 columns]

In [56]:
df[['Alcohol Consumption','Medical Conditions','Medications']]=np.where(df[['Alcohol Consumption','Medical Conditions','Medications']].isna(),'None',df[['Alcohol Consumption','Medical Conditions','Medications']])

# performing one hot encoding

In [63]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

In [64]:
encoder=OneHotEncoder(drop='first')
lencoder=LabelEncoder()

In [65]:
df['Alcohol Consumption']

0       Moderate
1           None
2       Moderate
3           None
4           None
          ...   
1953    Moderate
1954        None
1955        None
1956        None
1957        None
Name: Alcohol Consumption, Length: 1958, dtype: object

In [66]:
encoded_df=pd.DataFrame(encoder.fit_transform(df[['Gender','Hormonal Changes','Family History',
                                                  'Race/Ethnicity','Smoking','Prior Fractures','Medical Conditions']]).toarray(),columns=encoder.get_feature_names_out())
columns=['Body Weight','Calcium Intake','Vitamin D Intake','Physical Activity','Alcohol Consumption','Medications']
weight_bodyweight={'Underweight':0,
                'Normal':1}
mapped_data = [weight_bodyweight[label] for label in df['Body Weight']]
print(mapped_data)
calcium_mapping={'Low':0, 'Adequate':1}
cal_mapped_data=[calcium_mapping[i] for i in df['Calcium Intake']]
df['Calcium Intake']=cal_mapped_data
vit_mapping={'Sufficient':1 ,'Insufficient':0}
vit_mapped=[vit_mapping[i] for i in df['Vitamin D Intake']]
df['Vitamin D Intake']=vit_mapped
physical_mapping={'Sedentary':0,'Active':1}
phy_mapped=[physical_mapping[i] for i in df['Physical Activity']]
df['Physical Activity']=phy_mapped
aclholo_mapping={'Moderate':0,'None':1}
alco_mapped=[aclholo_mapping[i] for i in df['Alcohol Consumption']]
df['Alcohol Consumption']=alco_mapped
medic_mapping={'Corticosteroids':0,'None':1}
medi_mapped=[medic_mapping[i] for i in df['Medications']]
df['Medications']=medi_mapped


[0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 

In [67]:
df['Body Weight']=mapped_data

In [68]:
encoded_df.head()

Gender_Male  Hormonal Changes_Postmenopausal  Family History_Yes  \
0          0.0                              0.0                 1.0   
1          0.0                              0.0                 1.0   
2          0.0                              1.0                 0.0   
3          0.0                              0.0                 0.0   
4          1.0                              1.0                 1.0   

   Race/Ethnicity_Asian  Race/Ethnicity_Caucasian  Smoking_Yes  \
0                   1.0                       0.0          1.0   
1                   1.0                       0.0          0.0   
2                   0.0                       1.0          0.0   
3                   0.0                       1.0          1.0   
4                   0.0                       0.0          1.0   

   Prior Fractures_Yes  Medical Conditions_None  \
0                  1.0                      0.0   
1                  1.0                      1.0   
2                  0.0                      0.0   
3                  0.0                      0.0   
4                  1.0                      0.0   

   Medical Conditions_Rheumatoid Arthritis  
0                                      1.0  
1                                      0.0  
2                                      0.0  
3                                      1.0  
4                                      1.0

# joining the encoded df back to original df

In [69]:
df=pd.concat([df,encoded_df],axis=1)

In [70]:
df=df.drop(columns={'Gender','Race/Ethnicity','Hormonal Changes','Family History','Smoking','Prior Fractures','Medical Conditions'})

In [71]:
df.head()
df1= df.loc[:, df.columns != 'Osteoporosis'].join(df.loc[:, 'Osteoporosis'])
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [72]:
from sklearn.model_selection import train_test_split

In [73]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2, random_state=42)

# Applying linear regression on a binary classification problem to see how it performs

In [74]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

regressor=LinearRegression()
regressor.fit(xtrain,ytrain)
ypred=regressor.predict(xtest)

In [75]:
r_squared = r2_score(ytest, ypred)
print("R-squared:", r_squared*100)

R-squared: 27.242289100840534


In [76]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix,precision_score

# Using Logistic regression now

In [77]:
logistic=LogisticRegression(max_iter=1000)
logistic.fit(xtrain,ytrain)
ypred1=logistic.predict(xtest)
tn, fp, fn, tp = confusion_matrix(ytest, ypred1).ravel()
specificity = tn / (tn + fp)
print("Metrics for Logistic Regression model")
print("Accuracy",accuracy_score(ytest,ypred1))
print("Precision",precision_score(ytest,ypred1))
print("the confusion matrix is: ")
print(str(confusion_matrix(ytest,ypred1)))
print("specificity is: ",specificity)

Metrics for Logistic Regression model
Accuracy 0.6683673469387755
Precision 0.6
the confusion matrix is: 
[[232  20]
 [110  30]]
specificity is:  0.9206349206349206


# Decision Tree

In [78]:
df.groupby('Osteoporosis')['Osteoporosis'].count()

Osteoporosis
0    979
1    979
Name: Osteoporosis, dtype: int64

In [79]:
decision=DecisionTreeClassifier()
decision.fit(xtrain,ytrain)
ypred2=decision.predict(xtest)
print("Decision Tree metrics")
tn, fp, fn, tp = confusion_matrix(ytest, ypred2).ravel()
specificity = tn / (tn + fp)
print("Accuracy",accuracy_score(ytest,ypred2))
print("Precision",precision_score(ytest,ypred2))
print("the confusion matrix is: ")
print(str(confusion_matrix(ytest,ypred2)))
print("specificity is: ",specificity)

Decision Tree metrics
Accuracy 0.6454081632653061
Precision 0.5038759689922481
the confusion matrix is: 
[[188  64]
 [ 75  65]]
specificity is:  0.746031746031746


In [82]:
from sklearn.ensemble import RandomForestClassifier

In [83]:
randomf=RandomForestClassifier()
randomf.fit(xtrain,ytrain)
ypred3=randomf.predict(xtest)
print("Random Forest metrics")
tn, fp, fn, tp = confusion_matrix(ytest, ypred3).ravel()
specificity = tn / (tn + fp)
print("Accuracy",accuracy_score(ytest,ypred3))
print("Precision",precision_score(ytest,ypred3))
print("the confusion matrix is: ")
print(str(confusion_matrix(ytest,ypred3)))
print("specificity is: ",specificity)

Random Forest metrics
Accuracy 0.6632653061224489
Precision 0.5571428571428572
the confusion matrix is: 
[[221  31]
 [101  39]]
specificity is:  0.876984126984127


In [84]:
print("F1 scores of models")
print("Logistic regression",f1_score(ytest,ypred1))
print("Decision tree",f1_score(ytest,ypred2))
print("Random forest",f1_score(ytest,ypred3))

F1 scores of models
Logistic regression 0.3157894736842105
Decision tree 0.483271375464684
Random forest 0.37142857142857144


In [ ]:
#using grid search cv
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

# Define the parameter grid to search over
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['auto', 'sqrt']
}

# Initialize the Random Forest classifier
clf = RandomForestClassifier(random_state=42)

# Initialize the grid search with cross-validation
grid_search = GridSearchCV(estimator=clf, param_grid=param_grid, cv=5, scoring='accuracy')

# Fit the grid search to the training data
grid_search.fit(xtrain, ytrain)

# Get the best hyperparameters and model
best_params = grid_search.best_params_
best_model = grid_search.best_estimator_

# Evaluate the best model on the test data
accuracy = best_model.score(xtest, ytest)
print("Best Model Accuracy:", accuracy)
